// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/account.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PiggyMetrics.Common {

  /// <summary>Holder for reflection information generated from services/account.proto</summary>
  public static partial class AccountReflection {

    #region Descriptor
    /// <summary>File descriptor for services/account.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AccountReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZzZXJ2aWNlcy9hY2NvdW50LnByb3RvEgZkb3RicGUaE2RvdGJwZV9vcHRp",
            "b24ucHJvdG8aDW1lc3NhZ2UucHJvdG8yuQEKDkFjY291bnRTZXJ2aWNlEj4K",
            "CkZpbmRCeU5hbWUSFi5kb3RicGUuRmluZEFjY291bnRSZXEaEi5kb3RicGUu",
            "QWNjb3VudFJzcCIE0PMYARIwCgZDcmVhdGUSDC5kb3RicGUuVXNlchoSLmRv",
            "dGJwZS5BY2NvdW50UnNwIgTQ8xgCEi4KBFNhdmUSDy5kb3RicGUuQWNjb3Vu",
            "dBoPLmRvdGJwZS5Wb2lkUnNwIgTQ8xgDGgXI8xjpB0IcSAGqAhNQaWdneU1l",
            "dHJpY3MuQ29tbW9u8PMYAVAAUAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.ProtoBuf.DotbpeOptionReflection.Descriptor, global::PiggyMetrics.Common.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
