// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/notification.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PiggyMetrics.Common {

  /// <summary>Holder for reflection information generated from services/notification.proto</summary>
  public static partial class NotificationReflection {

    #region Descriptor
    /// <summary>File descriptor for services/notification.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NotificationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtzZXJ2aWNlcy9ub3RpZmljYXRpb24ucHJvdG8SBmRvdGJwZRoTZG90YnBl",
            "X29wdGlvbi5wcm90bxoNbWVzc2FnZS5wcm90bzJYChNOb3RpZmljYXRpb25T",
            "ZXJ2aWNlEjoKEFVwZGF0ZVN0YXRpc3RpY3MSDy5kb3RicGUuQWNjb3VudBoP",
            "LmRvdGJwZS5Wb2lkUnNwIgTQ8xgBGgXI8xjtB0IcSAGqAhNQaWdneU1ldHJp",
            "Y3MuQ29tbW9u8PMYAVAAUAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.ProtoBuf.DotbpeOptionReflection.Descriptor, global::PiggyMetrics.Common.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
