// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufObjectfactory
#region Designer generated code

using System; 
using System.Collections.Generic; 
using System.Text; 
using Google.Protobuf; 
using Google.Protobuf.Reflection; 

namespace PiggyMetrics.Common {
public class ProtobufObjectFactory {
public static IMessage GetRequestTemplate(int serviceId,int messageId)
{
if(serviceId == 1002 && messageId == 1){ return new User() ;
}
if(serviceId == 1002 && messageId == 2){ return new User() ;
}

if(serviceId == 1001 && messageId == 1){ return new FindAccountReq() ;
}
if(serviceId == 1001 && messageId == 2){ return new User() ;
}
if(serviceId == 1001 && messageId == 3){ return new Account() ;
}

if(serviceId == 1003 && messageId == 1){ return new Account() ;
}
if(serviceId == 1003 && messageId == 2){ return new FindAccountReq() ;
}

if(serviceId == 1004 && messageId == 1){ return new VoidReq() ;
}
if(serviceId == 1004 && messageId == 2){ return new ConvertReq() ;
}

if(serviceId == 1005 && messageId == 1){ return new Account() ;
}

return null;
}
public static IMessage GetResponseTemplate(int serviceId,int messageId)
{
if(serviceId == 1002 && messageId == 1){ return new VoidRsp() ;
}
if(serviceId == 1002 && messageId == 2){ return new AuthRsp() ;
}

if(serviceId == 1001 && messageId == 1){ return new Account() ;
}
if(serviceId == 1001 && messageId == 2){ return new Account() ;
}
if(serviceId == 1001 && messageId == 3){ return new VoidRsp() ;
}

if(serviceId == 1003 && messageId == 1){ return new VoidRsp() ;
}
if(serviceId == 1003 && messageId == 2){ return new StatRsp() ;
}

if(serviceId == 1004 && messageId == 1){ return new RateRsp() ;
}
if(serviceId == 1004 && messageId == 2){ return new ConvertRsp() ;
}

if(serviceId == 1005 && messageId == 1){ return new VoidRsp() ;
}

return null;
}
}
}
#endregion
