// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/statistic.proto
#region Designer generated code

using System; 
using System.Threading.Tasks; 
using DotBPE.Rpc; 
using DotBPE.Protocol.Amp; 
using Google.Protobuf; 

namespace PiggyMetrics.Common {

//start for class AbstractStatisticService
public abstract class StatisticServiceBase : IServiceActor<AmpMessage> 
{
public string Id => "1003$0";
//调用委托
private async Task ReceiveUpdateStatisticsAsync(IRpcContext<AmpMessage> context, AmpMessage req)
{
var request = Account.Parser.ParseFrom(req.Data);
var data = await UpdateStatisticsAsync(request);
var response = AmpMessage.CreateResponseMessage(req.ServiceId, req.MessageId);
response.Sequence = req.Sequence;
response.Data = data.ToByteArray();
await context.SendAsync(response);
}

//抽象方法
public abstract Task<VoidRsp> UpdateStatisticsAsync(Account request);
//调用委托
private async Task ReceiveFindByAccountAsync(IRpcContext<AmpMessage> context, AmpMessage req)
{
var request = FindAccountReq.Parser.ParseFrom(req.Data);
var data = await FindByAccountAsync(request);
var response = AmpMessage.CreateResponseMessage(req.ServiceId, req.MessageId);
response.Sequence = req.Sequence;
response.Data = data.ToByteArray();
await context.SendAsync(response);
}

//抽象方法
public abstract Task<StatRsp> FindByAccountAsync(FindAccountReq request);
public Task ReceiveAsync(IRpcContext<AmpMessage> context, AmpMessage req)
{
//方法StatisticService.UpdateStatistics
if(req.MessageId == 1){return this.ReceiveUpdateStatisticsAsync(context, req);}
//方法StatisticService.FindByAccount
if(req.MessageId == 2){return this.ReceiveFindByAccountAsync(context, req);}
return Task.CompletedTask;
}
}
//end for class AbstractStatisticService

//start for class AbstractExchangeService
public abstract class ExchangeServiceBase : IServiceActor<AmpMessage> 
{
public string Id => "1004$0";
//调用委托
private async Task ReceiveGetRatesAsync(IRpcContext<AmpMessage> context, AmpMessage req)
{
var request = VoidReq.Parser.ParseFrom(req.Data);
var data = await GetRatesAsync(request);
var response = AmpMessage.CreateResponseMessage(req.ServiceId, req.MessageId);
response.Sequence = req.Sequence;
response.Data = data.ToByteArray();
await context.SendAsync(response);
}

//抽象方法
public abstract Task<RateRsp> GetRatesAsync(VoidReq request);
//调用委托
private async Task ReceiveConvertAsync(IRpcContext<AmpMessage> context, AmpMessage req)
{
var request = ConvertReq.Parser.ParseFrom(req.Data);
var data = await ConvertAsync(request);
var response = AmpMessage.CreateResponseMessage(req.ServiceId, req.MessageId);
response.Sequence = req.Sequence;
response.Data = data.ToByteArray();
await context.SendAsync(response);
}

//抽象方法
public abstract Task<ConvertRsp> ConvertAsync(ConvertReq request);
public Task ReceiveAsync(IRpcContext<AmpMessage> context, AmpMessage req)
{
//方法ExchangeService.GetRates
if(req.MessageId == 1){return this.ReceiveGetRatesAsync(context, req);}
//方法ExchangeService.Convert
if(req.MessageId == 2){return this.ReceiveConvertAsync(context, req);}
return Task.CompletedTask;
}
}
//end for class AbstractExchangeService
}

#endregion

